version: '3.7'
services:
  ScriptProject:
    build:
      context: .
      dockerfile: Dockerfile
    image: script_image
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: script_project
    command: >
            bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
      

