# Generated by Django 5.0.2 on 2024-02-26 05:43

import apps.script.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[apps.script.models.validate_field]),
        ),
    ]
